### ISSUE TITLE
require_all_predictors default

### ISSUE THREAD

**Issue by DanielRichardBiber** [KHP-Informatics/ADR-graph#3]
Wondering if there is another place to set, require_all_predictors to 'False' other than "_init_"?  I was hoping to increase the number of models the 'predictAll' method would produce.  Switching the default value to 'False' did not seem to change the result.

`self.require_all_predictors = False` in the _init_ method

```
epall = ep.EdgePrediction()
s = epall.CSV_to_graph('data.csv', header=True, srcNameCol=0, srcTypeCol=1, tgtNameCol=4, tgtTypeCol=3, edgeTypeCol=2)
epall.preprocess()
epall.to_predict = 'HAS_SIDE_EFFECT'
epall.network_order = ['HAS_SIDE_EFFECT', 'DRUG_TARGETS', 'INDICATED_FOR']

AllResult = epall.predictAll(calculate_auc = True)
```

still produces several results that indicate:

```
self.require_all_predictors is True and x/3 networks have 0 predictor overlap
not optimizing a model for CXXXXX
```

Again my main goal is to just generate a higher percentage of models.  Thank you for your time and attention.

**Comment by dbeanm** [comment]
Good point, I'll move that. I would have thought your changes would have worked but what I do is set it afterwards:

```python
epall = ep.EdgePrediction()

epall.require_all_predictors = False

epall.CSV_to_graph( #etc
...
```
Does that work?

**Comment by DanielRichardBiber** [comment]
That change does enable the construction models for all predictors.  Thanks for your attention to the issues.
